name: Release to production

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write          # needed to create the release
  deployments: write       # recommended for environment/deployment updates

jobs:
  create_release:
    name: Create GitHub Release
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true

      - name: Build installer
        # build dist/installer.yaml using Kubebuilder tools
        run: |
          make build-installer IMG=scalingo/scalingo-operator:${{ github.ref_name }}
         
      - name: Create GitHub release and upload installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls dist
          gh release create "${{ github.ref_name }}" \
            "dist/install.yaml" \
            --title "${{ github.ref_name }}" \
            --generate-notes
