name: Release to production

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write          # needed to create the release
  deployments: write       # recommended for environment/deployment updates

jobs:
  create_release:
    name: Create GitHub Release
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: scalingo/scalingo-operator:${{ github.ref_name }}
          push: true

      - name: Build Kubernetes installer
        # build dist/installer.yaml using Kubebuilder tools
        run: |
          make build-installer IMG=scalingo/scalingo-operator:${{ github.ref_name }}
         
      - name: Create GitHub release and upload installer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls dist
          gh release create "${{ github.ref_name }}" \
            "dist/install.yaml" \
            --title "${{ github.ref_name }}" \
            --generate-notes
